In [2]:
import numpy as np
from subprocess import call


In [24]:
def get_matrix(pi1, pi2, q1, q2, l, sol_index=1):
    '''
    sol_index=1: the program that finds the solution always gets the good one on the second row of the file (when verbosity -v)
    '''
    r1, r2 = 1/q1, 1/q2
    # first get the stationary f0:
    call(f'python f0poly_sols_clean.py {pi1} {pi2} {q1} {q2} {l} -v > sols.dat', shell=True)
    sols = []
    with open('sols.dat', 'r') as file:
        for line in file.readlines():
            sols_i = [float(f) for f in line.split()]
            sols.append(sols_i)
    f0 = sols[sol_index][0]
    a11 = l*f0-r1-(1-l)*pi1*(1+l/(r1/f0-l))
    a12 = -pi1*(1-l)*(1+l/(r1/f0-l))
    a21 = -pi2*(1-l)*(1+l/(r2/f0-l))
    a22 = l*f0-r2-(1-l)*pi2*(1+l/(r2/f0-l))
    a = np.array([[a11,a12], [a21, a22]])
    return a


In [46]:
pi1, pi2, q1, q2, l = 0.2, 0.1, 7, 10, 0.45
a = get_matrix(pi1, pi2, q1, q2, l, sol_index=0)
print(np.linalg.eig(a)[0])

[0.53376669 0.5750278 ]


In [42]:
np.linalg.eig(a)

(array([-0.83054487,  0.04198367]),
 array([[-0.99656366,  0.68900161],
        [ 0.08283037, -0.72475981]]))

In [41]:
np.linalg.eig(a)[1][:,0]

array([-0.99656366,  0.08283037])